# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

jobs:
  main:
    docker:
      # specify the version
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/namhq1989/daily-toolkit

    steps:
      - checkout

      # remote docker
      - setup_remote_docker:
          docker_layer_caching: false

      # add ssh key, for login to server
      - add_ssh_keys:
          fingerprints:
            - "61:3c:09:a0:44:93:fc:eb:8d:ce:81:f2:37:31:54:1e"

      # login ECR
      - run:
          name: Login to Docker hub
          command: |
            echo $DOCKER_PWD | docker login -u $DOCKER_USERNAME --password-stdin

      # build the application image
      - run:
          name: Build && push docker image
          command: |
            docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE:latest -t $DOCKER_USERNAME/$DOCKER_IMAGE:$CIRCLE_SHA1 . 
            docker push $DOCKER_USERNAME/$DOCKER_IMAGE:latest
            docker push $DOCKER_USERNAME/$DOCKER_IMAGE:$CIRCLE_SHA1

      # deploy
      - run:
          name: Deploy to Google VM instance
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_HOSTNAME "/bin/bash /home/dev/deploy_app.sh $DOCKER_USERNAME/$DOCKER_IMAGE:$CIRCLE_SHA1"

# Workflows
workflows:
  version: 2
  build:
    jobs:
      - main:
          filters:
            branches:
              only:
                - develop
          context: release
